# Generated by Django 5.2.3 on 2025-06-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='post_videos/'),
        ),
    ]
