# Generated by Django 5.2.3 on 2025-07-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_field',
            field=models.CharField(blank=True, default='temp_value', max_length=50, null=True),
        ),
    ]
