# Generated by Django 5.2.3 on 2025-07-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_field',
        ),
    ]
