# Generated by Django 5.2.3 on 2025-08-06 21:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='art_section',
            field=models.CharField(choices=[('ACTING', 'Acting'), ('WRITING', 'Writing'), ('SINGING', 'Singing'), ('DANCING', 'Dancing'), ('PAINTING', 'Painting'), ('SCULPTURE', 'Sculpture'), ('PHOTOGRAPHY', 'Photography'), ('MUSIC_COMPOSITION', 'Music Composition'), ('DIRECTING', 'Directing'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
