# Generated by Django 5.2.3 on 2025-07-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='art_cv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
