# Generated by Django 5.2.3 on 2025-08-06 21:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_art_cv_artist_artistic_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='art_section',
            field=models.CharField(blank=True, choices=[('ACTING', 'Acting'), ('WRITING', 'Writing'), ('SINGING', 'Singing'), ('DANCING', 'Dancing'), ('PAINTING', 'Painting'), ('SCULPTURE', 'Sculpture'), ('PHOTOGRAPHY', 'Photography'), ('MUSIC_COMPOSITION', 'Music Composition'), ('DIRECTING', 'Directing'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='art_section',
            field=models.CharField(blank=True, choices=[('ACTING', 'Acting'), ('WRITING', 'Writing'), ('SINGING', 'Singing'), ('DANCING', 'Dancing'), ('PAINTING', 'Painting'), ('SCULPTURE', 'Sculpture'), ('PHOTOGRAPHY', 'Photography'), ('MUSIC_COMPOSITION', 'Music Composition'), ('DIRECTING', 'Directing'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
