# Generated by Django 5.2.3 on 2025-06-24 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text_content',
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='message',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='general_file',
        ),
        migrations.AddField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
